### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by albo1337** [frostney/react-native-bluetooth-state#2]
Hey @frostney 

I can't make a useable App to test this module. Could you make a simple example which shows the user that he has to turn bluetooth on first, to use the app using this module?

Would be great!

Thank you

**Comment by albo1337** [comment]
Hey @frostney 
is there any possibility to check if bluetooth is enabled when starting the app? The "centralManagerDidUpdateState"-event triggers only when the user changes the bluetooth state.

Thank you

**Comment by frostney** [comment]
I just release a new major version with an updated example. Feel free to leave suggestions or submit a pull request if feel like something is missing.
