### ISSUE TITLE
Check if bluetooth is enabled when app starts

### ISSUE THREAD

**Issue by albo1337** [frostney/react-native-bluetooth-state#3]
Hey @frostney 
is there any possibility to check if bluetooth is enabled when starting the app? The "centralManagerDidUpdateState"-event triggers only when the user changes the bluetooth state.

Thank you

albo1337

**Comment by bashmakoff** [comment]
There is a fork by @lisbakke
https://github.com/getchop/react-native-bluetooth-state/commits/master

But i didn't get what he has added. I have 0 experience in Objective-C
I'm looking for the feature **"Check the bluetooth state on the app start"** also

**Comment by frostney** [comment]
First of all, thank you for using my module and I'm super sorry I haven't been able to push the changes earlier.

I just released a new major version that implements the functionality of checking the bluetooth state on app start. Unfortunately that lead to major changes in the API. The important thing now is that you need to import the `react-native-bluetooth-native` module and call its `initialize` method:
```javascript
import BluetoothState from 'react-native-bluetooth-state';

BluetoothState.initialize();
```
You can still listen to the device emitter changes, although the recommended way now is to use `BluetoothState.subscribe` which is a convenience method around the device emitter listener.
**Important**: The event listener needs to be defined before the `initialize` call.
Please take a look at the readme or the updated example.

I really appreciate your feedback, so feel free to leave new issues with suggestions.

**Comment by albo1337** [comment]
Hi @frostney,

thank you for your update. It works fine. I have now an other problem. The alert window if the user hasnt turned on bluetooth isnt popping up anymore. This worked with your previous version, don't know what I'm doing wrong now.

best regards,
albo1337

**Comment by frostney** [comment]
Hi @albo1337, you are right. I removed that functionality for now as it was a bit hard for me to make that more configurable and I personally I found to be more annoying than helpful in my use case.
Feel free to create another issue for that specifically and I'll get to it as soon as I can.
